//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssoStMechLight.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IssoStMechLight.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] AddSection {
            get {
                object obj = ResourceManager.GetObject("AddSection", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Array {
            get {
                object obj = ResourceManager.GetObject("Array", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на расстояние.
        /// </summary>
        internal static string BindingDimValuePlaceholder {
            get {
                return ResourceManager.GetString("BindingDimValuePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Р. нагрузка.
        /// </summary>
        internal static string ButtonDstLoadLabel {
            get {
                return ResourceManager.GetString("ButtonDstLoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сила.
        /// </summary>
        internal static string ButtonForceLabel {
            get {
                return ResourceManager.GetString("ButtonForceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип опоры:.
        /// </summary>
        internal static string ButtonSupportTypeLabel {
            get {
                return ResourceManager.GetString("ButtonSupportTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Calculation {
            get {
                object obj = ResourceManager.GetObject("Calculation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на °.
        /// </summary>
        internal static string Degrees {
            get {
                return ResourceManager.GetString("Degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] delete88 {
            get {
                object obj = ResourceManager.GetObject("delete88", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DistLoad {
            get {
                object obj = ResourceManager.GetObject("DistLoad", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] FixedSupport {
            get {
                object obj = ResourceManager.GetObject("FixedSupport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Force {
            get {
                object obj = ResourceManager.GetObject("Force", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Hinge {
            get {
                object obj = ResourceManager.GetObject("Hinge", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] HorizDimension {
            get {
                object obj = ResourceManager.GetObject("HorizDimension", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] IconClose {
            get {
                object obj = ResourceManager.GetObject("IconClose", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на кН.
        /// </summary>
        internal static string KiloNewtons {
            get {
                return ResourceManager.GetString("KiloNewtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Linear {
            get {
                object obj = ResourceManager.GetObject("Linear", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инв..
        /// </summary>
        internal static string LoadInverse {
            get {
                return ResourceManager.GetString("LoadInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Типы сечений.
        /// </summary>
        internal static string MenuItemCrossSections {
            get {
                return ResourceManager.GetString("MenuItemCrossSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Элементы.
        /// </summary>
        internal static string MenuItemElements {
            get {
                return ResourceManager.GetString("MenuItemElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить.
        /// </summary>
        internal static string MenuItemLoad {
            get {
                return ResourceManager.GetString("MenuItemLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нагрузки.
        /// </summary>
        internal static string MenuItemLoads {
            get {
                return ResourceManager.GetString("MenuItemLoads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Материалы.
        /// </summary>
        internal static string MenuItemMaterials {
            get {
                return ResourceManager.GetString("MenuItemMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель.
        /// </summary>
        internal static string MenuItemModel {
            get {
                return ResourceManager.GetString("MenuItemModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Узлы.
        /// </summary>
        internal static string MenuItemNodes {
            get {
                return ResourceManager.GetString("MenuItemNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результаты.
        /// </summary>
        internal static string MenuItemResults {
            get {
                return ResourceManager.GetString("MenuItemResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить как.
        /// </summary>
        internal static string MenuItemSave {
            get {
                return ResourceManager.GetString("MenuItemSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        internal static string MenuItemSetup {
            get {
                return ResourceManager.GetString("MenuItemSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Mirror {
            get {
                object obj = ResourceManager.GetObject("Mirror", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить узел.
        /// </summary>
        internal static string ModelActionAddNode {
            get {
                return ResourceManager.GetString("ModelActionAddNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гор. размер.
        /// </summary>
        internal static string ModelActionDim {
            get {
                return ResourceManager.GetString("ModelActionDim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Угл. размер.
        /// </summary>
        internal static string ModelActionDimA {
            get {
                return ResourceManager.GetString("ModelActionDimA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Радиус.
        /// </summary>
        internal static string ModelActionDimR {
            get {
                return ResourceManager.GetString("ModelActionDimR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Верт. размер.
        /// </summary>
        internal static string ModelActionDimV {
            get {
                return ResourceManager.GetString("ModelActionDimV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шарнир.
        /// </summary>
        internal static string ModelActionHinge {
            get {
                return ResourceManager.GetString("ModelActionHinge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Линейный компонент.
        /// </summary>
        internal static string ModelActionLinearComponent {
            get {
                return ResourceManager.GetString("ModelActionLinearComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опора.
        /// </summary>
        internal static string ModelActionSupport {
            get {
                return ResourceManager.GetString("ModelActionSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расчёт.
        /// </summary>
        internal static string ModelCalcCaption {
            get {
                return ResourceManager.GetString("ModelCalcCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая.
        /// </summary>
        internal static string ModelNewLabel {
            get {
                return ResourceManager.GetString("ModelNewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NewModel {
            get {
                object obj = ResourceManager.GetObject("NewModel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Угол наклона к оси X:.
        /// </summary>
        internal static string NodeEditorAngleLabel {
            get {
                return ResourceManager.GetString("NodeEditorAngleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Координаты (x; y):.
        /// </summary>
        internal static string NodeEditorCoordinates {
            get {
                return ResourceManager.GetString("NodeEditorCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PinInternalSupport {
            get {
                object obj = ResourceManager.GetObject("PinInternalSupport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PinSupport {
            get {
                object obj = ResourceManager.GetObject("PinSupport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Redo {
            get {
                object obj = ResourceManager.GetObject("Redo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] rename {
            get {
                object obj = ResourceManager.GetObject("rename", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Rigid {
            get {
                object obj = ResourceManager.GetObject("Rigid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] RollerInternalSupport {
            get {
                object obj = ResourceManager.GetObject("RollerInternalSupport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] RollerSupport {
            get {
                object obj = ResourceManager.GetObject("RollerSupport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SelectFrame {
            get {
                object obj = ResourceManager.GetObject("SelectFrame", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номера элементов.
        /// </summary>
        internal static string SetupDisplayElementNumbers {
            get {
                return ResourceManager.GetString("SetupDisplayElementNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интенсивность нагрузок.
        /// </summary>
        internal static string SetupDisplayLoadValues {
            get {
                return ResourceManager.GetString("SetupDisplayLoadValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номера узлов.
        /// </summary>
        internal static string SetupDisplayNodeNumbers {
            get {
                return ResourceManager.GetString("SetupDisplayNodeNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Относительная жёсткость весом линий.
        /// </summary>
        internal static string SetupDisplayRigidity {
            get {
                return ResourceManager.GetString("SetupDisplayRigidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображение.
        /// </summary>
        internal static string SetupDisplayTitle {
            get {
                return ResourceManager.GetString("SetupDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязки.
        /// </summary>
        internal static string SetupSnapTitle {
            get {
                return ResourceManager.GetString("SetupSnapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка к сетке.
        /// </summary>
        internal static string SetupSnapToGrid {
            get {
                return ResourceManager.GetString("SetupSnapToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка к координатам узлов.
        /// </summary>
        internal static string SetupSnapToNodes {
            get {
                return ResourceManager.GetString("SetupSnapToNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ToSupport {
            get {
                object obj = ResourceManager.GetObject("ToSupport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Undo {
            get {
                object obj = ResourceManager.GetObject("Undo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] VertDimension {
            get {
                object obj = ResourceManager.GetObject("VertDimension", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ZoomAll {
            get {
                object obj = ResourceManager.GetObject("ZoomAll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ZoomIn {
            get {
                object obj = ResourceManager.GetObject("ZoomIn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ZoomOut {
            get {
                object obj = ResourceManager.GetObject("ZoomOut", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
